### ISSUE TITLE
Change 'charging' status to bolt icon

### ISSUE THREAD

**Issue by formap** [formap/pebble-pixel-grass#1]

**Comment by dasilvacontin** [comment]
with percent?

**Comment by formap** [comment]
Probably not since there are [issues](http://forums.getpebble.com/discussion/27918/batterychargestate-charge-percent-returning-crazy-numbers-when-charging-but-only-on-the-pebble-time#latest) with showing the percentage while the watch is charging.

**Comment by dasilvacontin** [comment]
Oh, shucks. Maybe when they fix it then.
